### ISSUE TITLE
[designspace backend] new layer glyph may be written before contents.plist

### ISSUE THREAD

**Issue by justvanrossum** [googlefonts/fontra#446]
Our watchfiles loop sees the changed .glif file, tries to update the glifLib glyph set, but is too early: the updated contents.plist may not have been written. This causes the glyph not to be seen in the glyph set.

I worked around this for the default source here:

https://github.com/googlefonts/fontra/blob/91ae89aeda5adb153b95a4448207a8efdd14399a/src/fontra/backends/designspace.py#L326-L337

But perhaps a different approach is needed.

**Comment by justvanrossum** [comment]
This may have been fixed by https://github.com/googlefonts/fontra/commit/2f00a72840f3d86534813b244cdad5895571ba2d, needs testing.

@martelahaie can you check with a fresh Fontra Pak when you have a moment? Adding a glyph to a non-default UFO source with RF, and see if Fontra responds to the change.

**Comment by martelahaie** [comment]
Tested with the latest Fontra Pak, with still the same result. Fontra only shows the glyphs added in RF in the default UFO

**Comment by justvanrossum** [comment]
Thank you! We'll debug further then.
